spring:
  data:
    mongodb:
      username: todo
      database: todo
      password: WjC120211
      host: cloudmo.top
      port: 27017
  redis:
    database: 0
    host: cloudmo.top
    password: wjc120211
    port: 6379
config:
  jwt:
    secret: sadfaewaf
    expire: 6000