spring:
  profiles:
    include: local
  session:
    store-type: redis
logging:
  level:
    root: error
server:
  port: 8088
  error:
    path: /error
  tomcat:
    uri-encoding: utf-8
    max-http-header-size: 10240000
    max-http-form-post-size: 10240000
  servlet:
    session:
      timeout: 30m
    context-path: /api/v1
  max-http-header-size: 10240000
  maxHttpHeaderSize: 102400
