spring:
  data:
    mongodb:
      username: todo
      database: todo
      password: localhost
      host: localhost
      port: 27017
  redis:
    database: 0
    host: localhost
    password: localhost
    port: 6379
config:
  jwt:
    secret: sadfaewaf
    expire: 6000